//go:build loong64

package reedsolomon

// galMulLSX folds n whole 32-byte blocks (16 big-endian uint16 words) of src into
// dst = src*coeff, and galMulAddLSX does dst ^= src*coeff, using the split-table
// vshuf.b byte-shuffle kernel generated by go-asmgen (galois_loong64_gen.go) into
// galois_loong64.s. tbl is the 128-byte coeff table built by buildSplitTables. The
// kernel uses only 128-bit LSX baseline ops (VMOVQ/VSHUFB/VANDB/VSRLB/VXORV/
// VILVLB/VILVHB), so it needs no build tag beyond loong64 and no feature check.
func galMulLSX(dst, src []byte, tbl *[128]byte, n int)
func galMulAddLSX(dst, src []byte, tbl *[128]byte, n int)

// useLSX gates the SIMD path. LSX is the loong64 baseline so this is always true
// in production; the differential test toggles it to cover the scalar fallback on
// loong64 too.
var useLSX = true

// galMul writes dst = src * coeff over GF(2^16). It folds whole 32-byte blocks
// with the vshuf.b split-table kernel and finishes the sub-block tail with the
// scalar oracle.
func galMul(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); useLSX && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulLSX(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulScalar(f, dst, src, coeff)
}

// galMulAdd accumulates dst ^= src * coeff over GF(2^16), folding whole 32-byte
// blocks with the vshuf.b kernel and deferring the tail to the scalar oracle.
func galMulAdd(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); useLSX && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulAddLSX(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulAddScalar(f, dst, src, coeff)
}
