// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·galMulVX(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD tbl+48(FP), R3
	MOVD n+56(FP), R4
	VL 0(R3), V16
	VL 16(R3), V17
	VL 32(R3), V18
	VL 48(R3), V19
	VL 64(R3), V20
	VL 80(R3), V21
	VL 96(R3), V22
	VL 112(R3), V23
	VREPIB $0x0f, V24
	MOVD $galEvenIdx<>(SB), R5
	VL 0(R5), V25
	MOVD $galOddIdx<>(SB), R5
	VL 0(R5), V26
	CMPBEQ R4, $0, done
loop:
	VL 0(R2), V0
	VL 16(R2), V1
	VPERM V0, V1, V25, V2
	VPERM V0, V1, V26, V3
	VN V24, V3, V4
	VESRLB $4, V3, V5
	VN V24, V2, V6
	VESRLB $4, V2, V7
	VPERM V16, V16, V4, V8
	VPERM V18, V18, V5, V9
	VX V9, V8, V8
	VPERM V20, V20, V6, V9
	VX V9, V8, V8
	VPERM V22, V22, V7, V9
	VX V9, V8, V8
	VPERM V17, V17, V4, V10
	VPERM V19, V19, V5, V9
	VX V9, V10, V10
	VPERM V21, V21, V6, V9
	VX V9, V10, V10
	VPERM V23, V23, V7, V9
	VX V9, V10, V10
	VMRHB V10, V8, V11
	VMRLB V10, V8, V12
	VST V11, 0(R1)
	VST V12, 16(R1)
	ADD $32, R2
	ADD $32, R1
	ADD $-1, R4
	CMPBNE R4, $0, loop
done:
	RET

TEXT ·galMulAddVX(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD tbl+48(FP), R3
	MOVD n+56(FP), R4
	VL 0(R3), V16
	VL 16(R3), V17
	VL 32(R3), V18
	VL 48(R3), V19
	VL 64(R3), V20
	VL 80(R3), V21
	VL 96(R3), V22
	VL 112(R3), V23
	VREPIB $0x0f, V24
	MOVD $galEvenIdx<>(SB), R5
	VL 0(R5), V25
	MOVD $galOddIdx<>(SB), R5
	VL 0(R5), V26
	CMPBEQ R4, $0, done
loop:
	VL 0(R2), V0
	VL 16(R2), V1
	VPERM V0, V1, V25, V2
	VPERM V0, V1, V26, V3
	VN V24, V3, V4
	VESRLB $4, V3, V5
	VN V24, V2, V6
	VESRLB $4, V2, V7
	VPERM V16, V16, V4, V8
	VPERM V18, V18, V5, V9
	VX V9, V8, V8
	VPERM V20, V20, V6, V9
	VX V9, V8, V8
	VPERM V22, V22, V7, V9
	VX V9, V8, V8
	VPERM V17, V17, V4, V10
	VPERM V19, V19, V5, V9
	VX V9, V10, V10
	VPERM V21, V21, V6, V9
	VX V9, V10, V10
	VPERM V23, V23, V7, V9
	VX V9, V10, V10
	VMRHB V10, V8, V11
	VMRLB V10, V8, V12
	VL 0(R1), V13
	VX V13, V11, V11
	VL 16(R1), V14
	VX V14, V12, V12
	VST V11, 0(R1)
	VST V12, 16(R1)
	ADD $32, R2
	ADD $32, R1
	ADD $-1, R4
	CMPBNE R4, $0, loop
done:
	RET

DATA galEvenIdx<>+0(SB)/1, $0x00
DATA galEvenIdx<>+1(SB)/1, $0x02
DATA galEvenIdx<>+2(SB)/1, $0x04
DATA galEvenIdx<>+3(SB)/1, $0x06
DATA galEvenIdx<>+4(SB)/1, $0x08
DATA galEvenIdx<>+5(SB)/1, $0x0a
DATA galEvenIdx<>+6(SB)/1, $0x0c
DATA galEvenIdx<>+7(SB)/1, $0x0e
DATA galEvenIdx<>+8(SB)/1, $0x10
DATA galEvenIdx<>+9(SB)/1, $0x12
DATA galEvenIdx<>+10(SB)/1, $0x14
DATA galEvenIdx<>+11(SB)/1, $0x16
DATA galEvenIdx<>+12(SB)/1, $0x18
DATA galEvenIdx<>+13(SB)/1, $0x1a
DATA galEvenIdx<>+14(SB)/1, $0x1c
DATA galEvenIdx<>+15(SB)/1, $0x1e
GLOBL galEvenIdx<>(SB), RODATA|NOPTR, $16

DATA galOddIdx<>+0(SB)/1, $0x01
DATA galOddIdx<>+1(SB)/1, $0x03
DATA galOddIdx<>+2(SB)/1, $0x05
DATA galOddIdx<>+3(SB)/1, $0x07
DATA galOddIdx<>+4(SB)/1, $0x09
DATA galOddIdx<>+5(SB)/1, $0x0b
DATA galOddIdx<>+6(SB)/1, $0x0d
DATA galOddIdx<>+7(SB)/1, $0x0f
DATA galOddIdx<>+8(SB)/1, $0x11
DATA galOddIdx<>+9(SB)/1, $0x13
DATA galOddIdx<>+10(SB)/1, $0x15
DATA galOddIdx<>+11(SB)/1, $0x17
DATA galOddIdx<>+12(SB)/1, $0x19
DATA galOddIdx<>+13(SB)/1, $0x1b
DATA galOddIdx<>+14(SB)/1, $0x1d
DATA galOddIdx<>+15(SB)/1, $0x1f
GLOBL galOddIdx<>(SB), RODATA|NOPTR, $16

