//go:build s390x

package reedsolomon

// galMulVX folds n whole 32-byte blocks (16 big-endian uint16 words) of src into
// dst = src*coeff, and galMulAddVX does dst ^= src*coeff, using the split-table
// VPERM byte-shuffle kernel generated by go-asmgen (galois_s390x_gen.go) into
// galois_s390x.s. tbl is the 128-byte coeff table built by buildSplitTables. The
// kernel uses only z13-baseline vector-facility ops (VL/VST/VPERM/VN/VX/VESRLB/
// VREPIB/VMRHB/VMRLB), so it needs no build tag beyond s390x and no runtime
// feature check.
func galMulVX(dst, src []byte, tbl *[128]byte, n int)
func galMulAddVX(dst, src []byte, tbl *[128]byte, n int)

// useVX gates the SIMD path. The vector facility is the s390x baseline so this is
// always true in production; the differential test toggles it to cover the scalar
// fallback on s390x too.
var useVX = true

// galMul writes dst = src * coeff over GF(2^16). It folds whole 32-byte blocks
// with the VPERM split-table kernel and finishes the sub-block tail with the
// scalar oracle.
func galMul(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); useVX && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulVX(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulScalar(f, dst, src, coeff)
}

// galMulAdd accumulates dst ^= src * coeff over GF(2^16), folding whole 32-byte
// blocks with the VPERM kernel and deferring the tail to the scalar oracle.
func galMulAdd(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); useVX && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulAddVX(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulAddScalar(f, dst, src, coeff)
}
