//go:build amd64

package reedsolomon

import "golang.org/x/sys/cpu"

// galMulSSSE3 folds n whole 32-byte blocks (16 big-endian uint16 words) of src
// into dst = src*coeff, and galMulAddSSSE3 does dst ^= src*coeff, using the
// split-table PSHUFB byte-shuffle kernel generated by go-asmgen
// (galois_amd64_gen.go) into galois_amd64.s. tbl is the 128-byte coeff table
// built by buildSplitTables. Both need SSSE3 (PSHUFB); the dispatch below checks
// for it and otherwise routes the whole region through the scalar oracle.
func galMulSSSE3(dst, src []byte, tbl *[128]byte, n int)
func galMulAddSSSE3(dst, src []byte, tbl *[128]byte, n int)

// hasSSSE3 gates the SIMD path. PSHUFB is SSSE3; the SSE2 baseline of amd64 does
// not include it, so this can be false on very old hosts (and is togglable by
// the differential test to cover the scalar fallback on amd64 too).
var hasSSSE3 = cpu.X86.HasSSSE3

// galMul writes dst = src * coeff over GF(2^16). It folds whole 32-byte blocks
// with the SSSE3 split-table kernel when available and finishes the sub-block
// tail with the scalar oracle; on a host without SSSE3 the whole region goes
// through the scalar loop.
func galMul(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); hasSSSE3 && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulSSSE3(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulScalar(f, dst, src, coeff)
}

// galMulAdd accumulates dst ^= src * coeff over GF(2^16), folding whole 32-byte
// blocks with the SSSE3 kernel and deferring the tail to the scalar oracle.
func galMulAdd(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); hasSSSE3 && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulAddSSSE3(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulAddScalar(f, dst, src, coeff)
}
