//go:build ppc64le

package reedsolomon

// galMulVSX folds n whole 32-byte blocks (16 big-endian uint16 words) of src into
// dst = src*coeff, and galMulAddVSX does dst ^= src*coeff, using the split-table
// VPERM byte-shuffle kernel generated by go-asmgen (galois_ppc64le_gen.go) into
// galois_ppc64le.s. tbl is the 128-byte coeff table built by buildSplitTables. The
// kernel uses only POWER8 (ISA 2.07) baseline VSX/VMX ops (LXVD2X/STXVD2X/VPERM/
// VAND/VSRB/VXOR/VSPLTISB), so it needs no build tag beyond ppc64le and no runtime
// feature check, and must not SIGILL on a POWER8 model.
func galMulVSX(dst, src []byte, tbl *[128]byte, n int)
func galMulAddVSX(dst, src []byte, tbl *[128]byte, n int)

// useVSX gates the SIMD path. VSX is the ppc64le baseline so this is always true in
// production; the differential test toggles it to cover the scalar fallback on
// ppc64le too.
var useVSX = true

// galMul writes dst = src * coeff over GF(2^16). It folds whole 32-byte blocks with
// the VPERM split-table kernel and finishes the sub-block tail with the scalar
// oracle.
func galMul(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); useVSX && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulVSX(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulScalar(f, dst, src, coeff)
}

// galMulAdd accumulates dst ^= src * coeff over GF(2^16), folding whole 32-byte
// blocks with the VPERM kernel and deferring the tail to the scalar oracle.
func galMulAdd(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); useVSX && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulAddVSX(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulAddScalar(f, dst, src, coeff)
}
