//go:build riscv64

package reedsolomon

import "golang.org/x/sys/cpu"

// galMulRVV folds n whole 32-byte blocks (16 big-endian uint16 words) of src into
// dst = src*coeff, and galMulAddRVV does dst ^= src*coeff, using the split-table
// vrgather.vv kernel generated by go-asmgen (galois_riscv64_gen.go) into
// galois_riscv64.s. tbl is the 128-byte coeff table built by buildSplitTables. The
// V instructions trap on a hart without the vector extension, so the dispatch below
// only calls them when hasV is set; otherwise the whole region uses the scalar
// oracle.
func galMulRVV(dst, src []byte, tbl *[128]byte, n int)
func galMulAddRVV(dst, src []byte, tbl *[128]byte, n int)

// hasV reports whether the RISC-V V (vector) extension is present. It gates the
// SIMD path; the differential test's length sweep exercises both the kernel path
// (large regions) and the scalar tail/skip (sub-block regions).
var hasV = cpu.RISCV64.HasV

// galMul writes dst = src * coeff over GF(2^16). With V present it folds whole
// 32-byte blocks with the vrgather split-table kernel and finishes the sub-block
// tail with the scalar oracle; without V the whole region uses the scalar loop.
func galMul(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); hasV && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulRVV(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulScalar(f, dst, src, coeff)
}

// galMulAdd accumulates dst ^= src * coeff over GF(2^16), folding whole 32-byte
// blocks with the vrgather kernel and deferring the tail to the scalar oracle.
func galMulAdd(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); hasV && n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulAddRVV(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulAddScalar(f, dst, src, coeff)
}
