//go:build arm64

package reedsolomon

// galMulNEON folds n whole 32-byte blocks (16 big-endian uint16 words) of src
// into dst = src*coeff, and galMulAddNEON does dst ^= src*coeff, using the
// split-table TBL byte-shuffle kernel generated by go-asmgen
// (galois_arm64_gen.go) into galois_arm64.s. tbl is the 128-byte coeff table
// built by buildSplitTables. The kernel uses only long-available NEON
// (VLD2/VST2 deinterleave, VTBL, VUSHR, VAND, VEOR), so it needs no build-tag
// beyond arm64.
func galMulNEON(dst, src []byte, tbl *[128]byte, n int)
func galMulAddNEON(dst, src []byte, tbl *[128]byte, n int)

// galMul writes dst = src * coeff over GF(2^16). It folds whole 32-byte blocks
// with the NEON split-table kernel and finishes the sub-block tail with the
// scalar oracle.
func galMul(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulNEON(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulScalar(f, dst, src, coeff)
}

// galMulAdd accumulates dst ^= src * coeff over GF(2^16), folding whole 32-byte
// blocks with the NEON kernel and deferring the tail to the scalar oracle.
func galMulAdd(f *GF16, dst, src []byte, coeff uint16) {
	if n := len(src) &^ (simdBlock - 1); n >= simdBlock {
		var tbl [128]byte
		buildSplitTables(f, coeff, &tbl)
		galMulAddNEON(dst[:n], src[:n], &tbl, n/simdBlock)
		dst, src = dst[n:], src[n:]
	}
	galMulAddScalar(f, dst, src, coeff)
}
